// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SallaAlertApp.Api.Data;

#nullable disable

namespace SallaAlertApp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SallaAlertApp.Api.Models.Merchant", b =>
                {
                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<string>("AlertEmail")
                        .HasColumnType("text")
                        .HasColumnName("alert_email");

                    b.Property<int>("AlertThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("alert_threshold");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("CustomWebhookUrl")
                        .HasColumnType("text")
                        .HasColumnName("custom_webhook_url");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("integer")
                        .HasColumnName("expires_in");

                    b.Property<bool>("NotifyEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_email");

                    b.Property<bool>("NotifyWebhook")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_webhook");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("text")
                        .HasColumnName("telegram_chat_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("MerchantId");

                    b.ToTable("Merchants", (string)null);
                });

            modelBuilder.Entity("SallaAlertApp.Api.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertsSentThisMonth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAlertsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTelegramAccounts")
                        .HasColumnType("integer");

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlanType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("SallaAlertApp.Api.Models.Subscription", b =>
                {
                    b.HasOne("SallaAlertApp.Api.Models.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });
#pragma warning restore 612, 618
        }
    }
}
